
import '../../../../../core/utils/assets.dart';

final List<Map<String, dynamic>> originalCartItems = [
  {
    'image': Assets.assetsImagesShirt,
    'name': 'Regular Fit Slogan',
    'size': 'L',
    'price': 1190,
    'quantity': 1,
    'category': 'Clothing',
    'rating': 4.5,
    'discountPercentage': 20,
    'isAvailable': true,
  },
  {
    'image': Assets.assetsImagesLaptop,
    'name': 'Laptop Pro 2024',
    'price': 2500,
    'quantity': 1,
    'category': 'Electronics',
    'rating': 4.7,
    'discountPercentage': 15,
    'isAvailable': true,
  },
  {
    'image': Assets.assetsImagesWashingMachine,
    'name': 'Washing Machine X100',
    'price': 1800,
    'quantity': 1,
    'category': 'Home Appliances',
    'rating': 4.0,
    'discountPercentage': 10,
    'isAvailable': false,
  },
  {
    'image': Assets.assetsImagesShirt,
    'name': 'Regular Fit Slogan',
    'size': 'L',
    'price': 1190,
    'quantity': 1,
    'category': 'Clothing',
    'rating': 4.5,
    'discountPercentage': 20,
    'isAvailable': true,
  },
  {
    'image': Assets.assetsImagesLaptop,
    'name': 'Laptop Pro 2024',
    'price': 2500,
    'quantity': 1,
    'category': 'Electronics',
    'rating': 4.7,
    'discountPercentage': 15,
    'isAvailable': true,
  },
  {
    'image': Assets.assetsImagesWashingMachine,
    'name': 'Washing Machine X100',
    'price': 1800,
    'quantity': 1,
    'category': 'Home Appliances',
    'rating': 4.0,
    'discountPercentage': 10,
    'isAvailable': false,
  },
  {
    'image': Assets.assetsImagesShirt,
    'name': 'Regular Fit Slogan',
    'size': 'L',
    'price': 1190,
    'quantity': 1,
    'category': 'Clothing',
    'rating': 4.5,
    'discountPercentage': 20,
    'isAvailable': true,
  },
  {
    'image': Assets.assetsImagesLaptop,
    'name': 'Laptop Pro 2024',
    'price': 2500,
    'quantity': 1,
    'category': 'Electronics',
    'rating': 4.7,
    'discountPercentage': 15,
    'isAvailable': true,
  },
  {
    'image': Assets.assetsImagesWashingMachine,
    'name': 'Washing Machine X100',
    'price': 1800,
    'quantity': 1,
    'category': 'Home Appliances',
    'rating': 4.0,
    'discountPercentage': 10,
    'isAvailable': false,
  },
  {
    'image': Assets.assetsImagesShirt,
    'name': 'Regular Fit Slogan',
    'size': 'L',
    'price': 1190,
    'quantity': 1,
    'category': 'Clothing',
    'rating': 4.5,
    'discountPercentage': 20,
    'isAvailable': true,
  },
  {
    'image': Assets.assetsImagesLaptop,
    'name': 'Laptop Pro 2024',
    'price': 2500,
    'quantity': 1,
    'category': 'Electronics',
    'rating': 4.7,
    'discountPercentage': 15,
    'isAvailable': true,
  },
  {
    'image': Assets.assetsImagesWashingMachine,
    'name': 'Washing Machine X100',
    'price': 1800,
    'quantity': 1,
    'category': 'Home Appliances',
    'rating': 4.0,
    'discountPercentage': 10,
    'isAvailable': false,
  },
];
